package com.makedream.jawasi.model;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig exerciseItemDaoConfig;
    private final DaoConfig exerciseItemDetailDaoConfig;
    private final DaoConfig stockDaoConfig;
    private final DaoConfig stockNoteDaoConfig;

    private final ExerciseItemDao exerciseItemDao;
    private final ExerciseItemDetailDao exerciseItemDetailDao;
    private final StockDao stockDao;
    private final StockNoteDao stockNoteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        exerciseItemDaoConfig = daoConfigMap.get(ExerciseItemDao.class).clone();
        exerciseItemDaoConfig.initIdentityScope(type);

        exerciseItemDetailDaoConfig = daoConfigMap.get(ExerciseItemDetailDao.class).clone();
        exerciseItemDetailDaoConfig.initIdentityScope(type);

        stockDaoConfig = daoConfigMap.get(StockDao.class).clone();
        stockDaoConfig.initIdentityScope(type);

        stockNoteDaoConfig = daoConfigMap.get(StockNoteDao.class).clone();
        stockNoteDaoConfig.initIdentityScope(type);

        exerciseItemDao = new ExerciseItemDao(exerciseItemDaoConfig, this);
        exerciseItemDetailDao = new ExerciseItemDetailDao(exerciseItemDetailDaoConfig, this);
        stockDao = new StockDao(stockDaoConfig, this);
        stockNoteDao = new StockNoteDao(stockNoteDaoConfig, this);

        registerDao(ExerciseItem.class, exerciseItemDao);
        registerDao(ExerciseItemDetail.class, exerciseItemDetailDao);
        registerDao(Stock.class, stockDao);
        registerDao(StockNote.class, stockNoteDao);
    }
    
    public void clear() {
        exerciseItemDaoConfig.getIdentityScope().clear();
        exerciseItemDetailDaoConfig.getIdentityScope().clear();
        stockDaoConfig.getIdentityScope().clear();
        stockNoteDaoConfig.getIdentityScope().clear();
    }

    public ExerciseItemDao getExerciseItemDao() {
        return exerciseItemDao;
    }

    public ExerciseItemDetailDao getExerciseItemDetailDao() {
        return exerciseItemDetailDao;
    }

    public StockDao getStockDao() {
        return stockDao;
    }

    public StockNoteDao getStockNoteDao() {
        return stockNoteDao;
    }

}
