package com.makedream.jawasi.model;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig execiseItemDaoConfig;
    private final DaoConfig stockDaoConfig;
    private final DaoConfig stockNoteDaoConfig;

    private final ExeciseItemDao execiseItemDao;
    private final StockDao stockDao;
    private final StockNoteDao stockNoteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        execiseItemDaoConfig = daoConfigMap.get(ExeciseItemDao.class).clone();
        execiseItemDaoConfig.initIdentityScope(type);

        stockDaoConfig = daoConfigMap.get(StockDao.class).clone();
        stockDaoConfig.initIdentityScope(type);

        stockNoteDaoConfig = daoConfigMap.get(StockNoteDao.class).clone();
        stockNoteDaoConfig.initIdentityScope(type);

        execiseItemDao = new ExeciseItemDao(execiseItemDaoConfig, this);
        stockDao = new StockDao(stockDaoConfig, this);
        stockNoteDao = new StockNoteDao(stockNoteDaoConfig, this);

        registerDao(ExeciseItem.class, execiseItemDao);
        registerDao(Stock.class, stockDao);
        registerDao(StockNote.class, stockNoteDao);
    }
    
    public void clear() {
        execiseItemDaoConfig.getIdentityScope().clear();
        stockDaoConfig.getIdentityScope().clear();
        stockNoteDaoConfig.getIdentityScope().clear();
    }

    public ExeciseItemDao getExeciseItemDao() {
        return execiseItemDao;
    }

    public StockDao getStockDao() {
        return stockDao;
    }

    public StockNoteDao getStockNoteDao() {
        return stockNoteDao;
    }

}
